name: xManager
version: 1.0.2
main: flxxd.xManager.Main
api-version: 1.18
depend: [ LuckPerms ]
authors: [ flxxd ]
description: lite LuckPerms API wrapper
website: tech.flink.gq/xmanager
commands:
  manager:
    aliases: ["xmanager"]
